import { StyleSheet } from "react-native";
import { colors, shadow, typography } from "../shared/theme";

export const passengerFareStyles = StyleSheet.create({
  map: { height: 300, borderRadius: 24, overflow: "hidden" },
  mapCanvas: { flex: 1 },
  mapHint: {
    position: "absolute",
    left: 14,
    right: 14,
    bottom: 14,
    borderRadius: 14,
    padding: 11,
    backgroundColor: "rgba(16,21,17,.86)",
    color: colors.surface,
    fontFamily: typography.semibold,
    fontSize: 12,
    textAlign: "center",
  },
  panel: { gap: 15 },
  segmented: {
    flexDirection: "row",
    gap: 7,
    borderRadius: 14,
    padding: 4,
    backgroundColor: colors.surfaceSoft,
  },
  segment: {
    flex: 1,
    minHeight: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
  },
  segmentActive: { backgroundColor: colors.surface, ...shadow },
  segmentText: {
    color: colors.muted,
    fontFamily: typography.semibold,
    fontSize: 11,
    textAlign: "center",
  },
  segmentTextActive: { color: colors.ink },
  verified: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    borderRadius: 16,
    padding: 13,
    backgroundColor: "#EAF8E6",
  },
  verifiedText: {
    flex: 1,
    color: colors.forest,
    fontFamily: typography.semibold,
    fontSize: 12,
    lineHeight: 18,
  },
  estimate: {
    borderRadius: 22,
    padding: 18,
    gap: 13,
    backgroundColor: colors.ink,
  },
  estimateTop: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  estimateLabel: {
    color: "#B6C1B9",
    fontFamily: typography.semibold,
    fontSize: 11,
    textTransform: "uppercase",
  },
  estimateFare: {
    color: colors.lime,
    fontFamily: typography.extraBold,
    fontSize: 34,
  },
  estimateDistance: {
    color: colors.surface,
    fontFamily: typography.bold,
    fontSize: 14,
  },
  estimateMeta: {
    color: "#B6C1B9",
    fontFamily: typography.regular,
    fontSize: 11,
    lineHeight: 16,
  },
  active: { borderColor: colors.limeDark, backgroundColor: "#EEFAEB" },
  activeFare: {
    color: colors.forest,
    fontFamily: typography.extraBold,
    fontSize: 30,
  },
  place: { flexDirection: "row", gap: 10, alignItems: "flex-start" },
  placeText: {
    flex: 1,
    color: colors.charcoal,
    fontFamily: typography.medium,
    fontSize: 12,
    lineHeight: 18,
  },
  disabled: { opacity: 0.45 },
});
