import { StyleSheet } from "react-native";
import { colors, typography } from "../shared/theme";

export const passengerScannerStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#080C09" },
  camera: { flex: 1 },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "space-between",
    padding: 24,
    paddingTop: 64,
    paddingBottom: 130,
  },
  intro: { alignItems: "center", gap: 8 },
  title: {
    color: colors.surface,
    fontFamily: typography.extraBold,
    fontSize: 26,
  },
  subtitle: {
    maxWidth: 310,
    color: "#CFD8D1",
    fontFamily: typography.regular,
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
  },
  frame: {
    alignSelf: "center",
    width: 248,
    height: 248,
    borderWidth: 3,
    borderColor: colors.lime,
    borderRadius: 30,
    backgroundColor: "transparent",
  },
  hint: {
    alignSelf: "center",
    overflow: "hidden",
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 10,
    color: colors.surface,
    backgroundColor: "rgba(0,0,0,.66)",
    fontFamily: typography.semibold,
    fontSize: 12,
  },
  permission: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    padding: 28,
    backgroundColor: colors.canvas,
  },
  resultBackdrop: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(7,12,9,.62)",
  },
  resultCard: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 22,
    paddingBottom: 38,
    gap: 15,
    backgroundColor: colors.surface,
  },
  resultHeader: { flexDirection: "row", alignItems: "center", gap: 12 },
  resultIcon: {
    width: 46,
    height: 46,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E7F9E2",
  },
  resultTitle: {
    flex: 1,
    color: colors.ink,
    fontFamily: typography.bold,
    fontSize: 19,
  },
  resultMessage: {
    color: colors.muted,
    fontFamily: typography.regular,
    fontSize: 13,
    lineHeight: 19,
  },
  detailGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  detail: {
    width: "48%",
    borderRadius: 14,
    padding: 12,
    backgroundColor: colors.surfaceSoft,
  },
  detailLabel: {
    color: colors.muted,
    fontFamily: typography.medium,
    fontSize: 10,
    textTransform: "uppercase",
  },
  detailValue: {
    marginTop: 4,
    color: colors.ink,
    fontFamily: typography.bold,
    fontSize: 13,
  },
  actions: { flexDirection: "row", gap: 10 },
  action: { flex: 1 },
});
