import { StyleSheet } from "react-native";
import { colors, shadow, typography } from "../shared/theme";

export const passengerHomeStyles = StyleSheet.create({
  backdrop: { flex: 1, backgroundColor: colors.canvas },
  headerCard: {
    borderWidth: 1,
    borderColor: "#D6E6D7",
    borderRadius: 25,
    padding: 18,
    backgroundColor: "#F2F9EF",
    ...shadow,
  },
  headerTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  greeting: {
    color: colors.limeDark,
    fontFamily: typography.bold,
    fontSize: 10,
    letterSpacing: 1.7,
    textTransform: "uppercase",
  },
  username: {
    marginTop: 7,
    color: colors.ink,
    fontFamily: typography.extraBold,
    fontSize: 27,
    letterSpacing: -0.7,
  },
  date: {
    marginTop: 4,
    color: colors.muted,
    fontFamily: typography.medium,
    fontSize: 11,
  },
  headerActions: { flexDirection: "row", alignItems: "center", gap: 10 },
  circleButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 22,
    backgroundColor: colors.surface,
  },
  avatarButton: { position: "relative" },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.ink,
  },
  avatarFallback: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 24,
    backgroundColor: colors.ink,
  },
  avatarText: { color: colors.lime, fontFamily: typography.bold, fontSize: 14 },
  avatarCamera: {
    position: "absolute",
    right: -3,
    bottom: -3,
    width: 21,
    height: 21,
    borderWidth: 2,
    borderColor: "#F2F9EF",
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.lime,
  },
  hero: {
    overflow: "hidden",
    borderRadius: 25,
    padding: 22,
    backgroundColor: colors.ink,
    ...shadow,
  },
  heroBlue: { backgroundColor: "#153C4A" },
  heroWarm: { backgroundColor: "#3D3218" },
  heroViewport: { marginHorizontal: -20 },
  heroSlide: { paddingHorizontal: 20 },
  heroBadge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "#183A24",
  },
  heroBadgeText: {
    color: colors.lime,
    fontFamily: typography.bold,
    fontSize: 10,
    letterSpacing: 1.1,
  },
  heroTitle: {
    width: "82%",
    marginTop: 18,
    color: colors.surface,
    fontFamily: typography.extraBold,
    fontSize: 24,
    lineHeight: 31,
    letterSpacing: -0.5,
  },
  heroBody: {
    width: "88%",
    marginTop: 9,
    color: "#BBC5BE",
    fontFamily: typography.regular,
    fontSize: 13,
    lineHeight: 20,
  },
  heroActions: { flexDirection: "row", gap: 10, marginTop: 20 },
  heroPrimary: {
    flex: 1,
    minHeight: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 15,
    backgroundColor: colors.lime,
  },
  heroSecondary: {
    flex: 1,
    minHeight: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "#39433D",
    borderRadius: 15,
  },
  heroPrimaryText: {
    color: colors.ink,
    fontFamily: typography.bold,
    fontSize: 13,
  },
  heroSecondaryText: {
    color: colors.surface,
    fontFamily: typography.semibold,
    fontSize: 13,
  },
  pageDots: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 6,
    marginTop: 10,
  },
  pageDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: "#C9D1CB" },
  pageDotActive: { width: 19, backgroundColor: colors.limeDark },
  sectionHeader: { marginTop: 4 },
  sectionTitle: {
    color: colors.ink,
    fontFamily: typography.bold,
    fontSize: 18,
  },
  sectionSubtitle: {
    marginTop: 2,
    color: colors.muted,
    fontFamily: typography.regular,
    fontSize: 11,
  },
  statGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  stat: {
    width: "48%",
    minHeight: 112,
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 19,
    padding: 14,
    backgroundColor: colors.surface,
  },
  statGreen: { backgroundColor: "#EAF7E8" },
  statBlue: { backgroundColor: "#EAF3FA" },
  statIcon: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.7)",
  },
  statValue: {
    color: colors.ink,
    fontFamily: typography.extraBold,
    fontSize: 23,
  },
  statLabel: {
    color: colors.muted,
    fontFamily: typography.medium,
    fontSize: 11,
  },
  quickGrid: { flexDirection: "row", gap: 9 },
  quickAction: {
    flex: 1,
    minHeight: 92,
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 18,
    backgroundColor: colors.surface,
  },
  quickIcon: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: colors.surfaceSoft,
  },
  quickIconDanger: { backgroundColor: colors.dangerSoft },
  quickText: {
    color: colors.charcoal,
    fontFamily: typography.semibold,
    fontSize: 10,
  },
  recentCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 17,
    padding: 13,
    backgroundColor: colors.surface,
  },
  recentIcon: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: colors.surfaceSoft,
  },
  recentCopy: { flex: 1 },
  recentTitle: {
    color: colors.ink,
    fontFamily: typography.semibold,
    fontSize: 13,
  },
  recentMeta: {
    marginTop: 3,
    color: colors.muted,
    fontFamily: typography.regular,
    fontSize: 10,
  },
  fare: { color: colors.forest, fontFamily: typography.bold, fontSize: 13 },
  modalBackdrop: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(9,15,11,.48)",
  },
  notificationSheet: {
    minHeight: 250,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 22,
    paddingBottom: 38,
    gap: 16,
    backgroundColor: colors.canvas,
  },
  notificationTitle: {
    color: colors.ink,
    fontFamily: typography.extraBold,
    fontSize: 22,
  },
  notificationEmpty: {
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 35,
  },
});
