import { StyleSheet } from "react-native";
import { colors, shadow, typography } from "../shared/theme";

export const passengerProfileStyles = StyleSheet.create({
  hero: {
    alignItems: "center",
    gap: 8,
    borderRadius: 26,
    padding: 22,
    backgroundColor: "#EAF7E6",
  },
  avatarWrap: { position: "relative" },
  avatar: {
    width: 92,
    height: 92,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.ink,
    ...shadow,
  },
  avatarImage: { width: 92, height: 92, borderRadius: 30 },
  initials: {
    color: colors.lime,
    fontFamily: typography.extraBold,
    fontSize: 26,
  },
  camera: {
    position: "absolute",
    right: -7,
    bottom: -7,
    width: 34,
    height: 34,
    borderWidth: 3,
    borderColor: "#EAF7E6",
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.lime,
  },
  name: { color: colors.ink, fontFamily: typography.extraBold, fontSize: 22 },
  username: {
    color: colors.muted,
    fontFamily: typography.medium,
    fontSize: 13,
  },
  verified: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: colors.surface,
  },
  verifiedText: {
    color: colors.forest,
    fontFamily: typography.bold,
    fontSize: 10,
    textTransform: "uppercase",
  },
  group: {
    overflow: "hidden",
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 20,
    backgroundColor: colors.surface,
  },
  menu: {
    minHeight: 62,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 15,
  },
  menuIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
  },
  menuCopy: { flex: 1 },
  menuTitle: {
    color: colors.ink,
    fontFamily: typography.semibold,
    fontSize: 14,
  },
  menuSubtitle: {
    marginTop: 2,
    color: colors.muted,
    fontFamily: typography.regular,
    fontSize: 11,
  },
  separator: {
    height: StyleSheet.hairlineWidth,
    marginLeft: 65,
    backgroundColor: colors.line,
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(9,15,11,.58)",
  },
  sheet: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 22,
    paddingBottom: 38,
    gap: 13,
    backgroundColor: colors.canvas,
  },
  sheetTitle: {
    color: colors.ink,
    fontFamily: typography.extraBold,
    fontSize: 22,
  },
  danger: { color: colors.danger },
});
