import { StyleSheet } from "react-native";
import { colors, typography } from "../shared/theme";

export const driverProfileStyles = StyleSheet.create({
  hero: {
    alignItems: "center",
    gap: 7,
    borderRadius: 25,
    padding: 22,
    backgroundColor: "#EAF7E6",
  },
  avatarWrap: { position: "relative" },
  avatar: {
    width: 88,
    height: 88,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.ink,
  },
  avatarImage: { width: 88, height: 88, borderRadius: 28 },
  initials: {
    color: colors.lime,
    fontFamily: typography.extraBold,
    fontSize: 25,
  },
  camera: {
    position: "absolute",
    right: -6,
    bottom: -6,
    width: 33,
    height: 33,
    borderWidth: 3,
    borderColor: "#EAF7E6",
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.lime,
  },
  name: { color: colors.ink, fontFamily: typography.extraBold, fontSize: 21 },
  username: {
    color: colors.muted,
    fontFamily: typography.medium,
    fontSize: 12,
  },
  row: { flexDirection: "row", gap: 12, paddingVertical: 8 },
  label: {
    width: 112,
    color: colors.muted,
    fontFamily: typography.regular,
    fontSize: 11,
  },
  value: {
    flex: 1,
    color: colors.ink,
    fontFamily: typography.semibold,
    fontSize: 11,
  },
  stats: { flexDirection: "row", gap: 9 },
  stat: {
    flex: 1,
    alignItems: "center",
    borderRadius: 16,
    padding: 13,
    backgroundColor: colors.surface,
  },
  statValue: {
    color: colors.ink,
    fontFamily: typography.extraBold,
    fontSize: 20,
  },
  statLabel: {
    marginTop: 3,
    color: colors.muted,
    fontFamily: typography.medium,
    fontSize: 9,
    textAlign: "center",
  },
  group: { gap: 12 },
  violation: { gap: 6 },
  violationTitle: {
    color: colors.ink,
    fontFamily: typography.bold,
    fontSize: 13,
  },
  violationMeta: {
    color: colors.muted,
    fontFamily: typography.regular,
    fontSize: 11,
    lineHeight: 17,
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(9,15,11,.58)",
  },
  sheet: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 22,
    paddingBottom: 38,
    gap: 13,
    backgroundColor: colors.canvas,
  },
  sheetTitle: {
    color: colors.ink,
    fontFamily: typography.extraBold,
    fontSize: 22,
  },
  dangerText: {
    color: colors.danger,
    fontFamily: typography.bold,
    fontSize: 13,
  },
});
