import { StyleSheet } from "react-native";
import { colors, shadow, typography } from "./theme";

export const commonStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.canvas },
  screen: { flex: 1, backgroundColor: colors.canvas },
  scrollContent: { padding: 20, paddingBottom: 120, gap: 16 },
  title: {
    color: colors.ink,
    fontFamily: typography.extraBold,
    fontSize: 26,
    letterSpacing: -0.7,
  },
  sectionTitle: {
    color: colors.ink,
    fontFamily: typography.bold,
    fontSize: 18,
    letterSpacing: -0.3,
  },
  eyebrow: {
    color: colors.limeDark,
    fontFamily: typography.bold,
    fontSize: 11,
    letterSpacing: 1.5,
    textTransform: "uppercase",
  },
  body: {
    color: colors.muted,
    fontFamily: typography.regular,
    fontSize: 14,
    lineHeight: 21,
  },
  caption: {
    color: colors.muted,
    fontFamily: typography.medium,
    fontSize: 12,
    lineHeight: 17,
  },
  card: {
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 20,
    padding: 17,
    backgroundColor: colors.surface,
    ...shadow,
  },
  button: {
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    borderRadius: 15,
    paddingHorizontal: 18,
    backgroundColor: colors.lime,
  },
  buttonText: { color: colors.ink, fontFamily: typography.bold, fontSize: 14 },
  secondaryButton: {
    minHeight: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 15,
    paddingHorizontal: 16,
    backgroundColor: colors.surface,
  },
  secondaryButtonText: {
    color: colors.ink,
    fontFamily: typography.semibold,
    fontSize: 14,
  },
  input: {
    minHeight: 52,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 14,
    paddingHorizontal: 15,
    color: colors.ink,
    backgroundColor: colors.surface,
    fontFamily: typography.medium,
    fontSize: 14,
  },
  label: {
    marginBottom: 7,
    color: colors.charcoal,
    fontFamily: typography.semibold,
    fontSize: 12,
  },
  row: { flexDirection: "row", alignItems: "center" },
  rowBetween: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  badge: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: colors.surfaceSoft,
  },
  badgeText: {
    color: colors.forest,
    fontFamily: typography.bold,
    fontSize: 10,
    textTransform: "uppercase",
  },
  divider: { height: StyleSheet.hairlineWidth, backgroundColor: colors.line },
  empty: { alignItems: "center", gap: 8, paddingVertical: 32 },
  error: {
    color: colors.danger,
    fontFamily: typography.medium,
    fontSize: 12,
    lineHeight: 18,
  },
});
