import { StyleSheet } from "react-native";
import { colors, shadow, typography } from "../shared/theme";

export const loginStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.canvas },
  content: { flexGrow: 1, justifyContent: "center", padding: 22 },
  brand: { alignItems: "center", marginBottom: 24 },
  logo: {
    width: 64,
    height: 64,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 21,
    backgroundColor: colors.ink,
    ...shadow,
  },
  brandName: {
    marginTop: 12,
    color: colors.ink,
    fontFamily: typography.extraBold,
    fontSize: 28,
    letterSpacing: -1,
  },
  brandAccent: { color: colors.limeDark },
  subtitle: {
    marginTop: 6,
    color: colors.muted,
    fontFamily: typography.regular,
    fontSize: 13,
    textAlign: "center",
  },
  card: {
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 24,
    padding: 20,
    backgroundColor: colors.surface,
    ...shadow,
  },
  heading: {
    color: colors.ink,
    fontFamily: typography.extraBold,
    fontSize: 23,
    letterSpacing: -0.6,
  },
  helper: {
    marginTop: 5,
    marginBottom: 18,
    color: colors.muted,
    fontFamily: typography.regular,
    fontSize: 13,
    lineHeight: 19,
  },
  selector: {
    flexDirection: "row",
    marginBottom: 18,
    borderRadius: 14,
    padding: 4,
    backgroundColor: colors.surfaceSoft,
  },
  selectorButton: {
    flex: 1,
    minHeight: 43,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderRadius: 11,
  },
  selectorActive: { backgroundColor: colors.surface, ...shadow },
  selectorText: {
    color: colors.muted,
    fontFamily: typography.semibold,
    fontSize: 12,
  },
  selectorTextActive: { color: colors.ink },
  field: { marginBottom: 13 },
  passwordWrap: { position: "relative" },
  passwordInput: { paddingRight: 52 },
  eyeButton: {
    position: "absolute",
    right: 4,
    top: 4,
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  button: { marginTop: 5 },
  apiHint: {
    marginTop: 14,
    color: colors.subtle,
    fontFamily: typography.regular,
    fontSize: 10,
    lineHeight: 15,
    textAlign: "center",
  },
});
